server:
  port: 8761

spring:
  application:
    name: discoverservice

# all server with dependency is recognized as eureka client in default
# so, it should be set for server
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
